language: php
php:
    - 5.6
    - 7.0
install:
    - composer install
script:
    - mkdir -p build/logs
    - php bin/phpunit --bootstrap app/bootstrap.php.cache --coverage-clover clover.xml src/
after_script:
    - php bin/coveralls
