language: php
php:
    - 5.6
    - 7.0
install:
    - composer install
script:
    - mkdir -p build/logs
    - chmod 777 build/logs
    - cp app/phpunit.xml.dist app/phpunit.xml
    - php bin/phpunit --bootstrap app/bootstrap.php.cache --coverage-clover build/logs/clover.xml -c app/phpunit.xml src/
