services:

    querker.strategy.filelock:
        class: Querker\QueueBundle\Strategy\FileLockStrategy
        arguments: ["%kernel.root_dir%/cache/queue.bin"]

    querker.queue_manager:
        class: Querker\QueueBundle\Manager\QueueManager
        arguments: [@querker.strategy.filelock]

    querker.processor:
        class: Querker\WorkerBundle\Processor\Processor
        arguments: [@querker.queue_manager, 30, 3]